learning_log/urls.py
#manage URLs for admin site
from django.contrib import admin

#path module mathcess URLs to views
from django.urls import path, include

#list of URLs from all apps in the project
urlpatterns = [

    #admin.site.urls defines all URLs that can be requested from admin site
    #this is the path for the admin site
    #When URL is followed by admin/ brings us to admin site
    path('admin/', admin.site.urls),

    #URLs for users app
    #users app contains all stuff working with users(registration, authorization)
    #users app URL is base + users/
    #imports/calls users app (users.urls)
    path('users/', include("users.urls")),

    #URLs for learning_logs app
    #imports module/file learning_logs.urls
    #base URL calls learning_logs.urls
    path('', include("learning_logs.urls")),


]

learning_logs/urls.py
"""Defines URL patterns for learning_logs"""

#maps/matches URLs to views
from django.urls import path

#(.) means that views is from same directory as urls
from . import views

#specifies that this urls.py file is for learning_logs
app_name = "learning_logs"

#individual pages that can be requested from learning logs app
#subset of pages specifically for this app
urlpatterns = [

#Home page
    #3 arguments
    #1. string to route request to match a view
        #empty string matches local base URL
    #2. which function to call in views.py when match is made
        #index function
    #3. alternate name for URL pattern, replaces actual URL
    path('', views.index, name = 'index'),

#page that shows all topics
    #base URL + topics/ will be url to match to get template
    #calls views.topics
    path("topics/", views.topics, name="topics"),

#page for a single topic
    #each topic will have its own page, based on view, url, & template
    #base URL + topics + id
    #<>, matches integer value to topic_id
    #topic id will be matched to specific topic
    path("topics/<int:topic_id>/", views.topic, name = "topic"),

#page for adding a new topic
    path("new_topic/", views.new_topic, name ="new_topic"),

#page for adding a new entry
#topic id is included cuz we're adding an entry for a specific topic
#topic_id thus has to match number specified
    path("new_entry/<int:topic_id>/", views.new_entry, name="new_entry"),

#page for editing an entry
#each entry has an id number and is in a queryset for a specific topic
#topic.entry_set.get(id))
    path("edit_entry/<int:entry_id>/", views.edit_entry, name="edit_entry"),

]

users/urls.py
"""Defines URL patterns for users"""

#path function provides path from URL to view
#view function allows us to call default django authentication URL
from django.urls import path, include

from . import views

#can distinguish URLs from other apps (learning_logs)
app_name = "users"

urlpatterns = [

    #include default auth urls
    #login page, calls django's default login/logout views
    #we don't have to create a view for this page request
    path("", include("django.contrib.auth.urls")),

    #registration page
    #there is no default registration view so we import views
    #URL is base for users app + register
    path("register/", views.register, name="register"),


]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

#define a model(class)
#tells us what to do with data
#define a model for every Topic users store
#Parent Model class defines a models functionality
class Topic(models.Model):
    """A topic the user is learning about"""

    #attribute for text, CharField is characer/text object
    #max amount of characters is 200
    text = models.CharField(max_length=200)

    #DateTimeField records date and time
    #argument auto_now_add means record current
    # time when user adds a topic
    date_added = models.DateTimeField(auto_now_add=True)

    #attribute of owner, which has relationship with topic
    #ForeignKey = User(owner) is key, Topics are values
    #User is default model
    #CASCADE = if user is deleted, so are topics
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    #method that converts object to string automatically
    def __str__(self):
        """Return a string representation of the model"""
        return self.text


#Entry inherits from djangos Model class
class Entry(models.Model):
    """Something specific learned about a topic"""

    #topic attribute is reference to Topic
    #foreign key connects each entry to specfic topic
    #each topic has ID/key
    #Cascade argument means that when a topic is deleted so
    # are all entries
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)

    #text attribute different from that of Topic
    #no size limit like Charfield
    text = models.TextField()

    #same attribute defined as in Topic
    date_added = models.DateTimeField(auto_now_add=True)

    #nested class
    #Meta holds extra info for models
    #use Entries when referriing to more than one entry
    class Meta:
        verbose_name_plural = "entries"

    def __str__(self):
        "Return a string representation of the model"

        #this refers to the admin interface
        #convert text to string
        #only show first 50 characters of string in admin interface
        return f"{self.text[:50]}..."

learning_logs/forms.py
#form = page that lets user input info
#we must validate and store info
from django import forms

#Topic is first model we work with, same directory
#aslo work with Entry model, allow us to submit data as entry
from .models import Topic, Entry

#ModelForm class uses info from models to create a form
class TopicForm(forms.ModelForm):

    # Meta tells django which model to build form
    # AND what fields to have in form
    class Meta:

        #build form from Topic model
        model = Topic

        #we include the text as a field (not date_added)
        # we dont include a label for the field
        fields = ['text']
        labels = {"text": ""}


class EntryForm(forms.ModelForm):
    class Meta:

        #build form from Entry model
        model = Entry

        #user can submit text, (not date added)
        fields = ["text"]

        #text field is not labeled
        labels = {"text": ""}

        #widget is HTML form element, (text box, list, etc.)
        #this line overrides default widget attributes
        #text area will be 80 columns wide(usual is 40)
        widgets = {"text": forms.Textarea(attrs={"cols":80})}

learning_logs/views.py
#view takes info from request, prepares and sends data for page
#uses template to define what page will look like

#render function gives response based on data from view
#redirect function redirects user to specific page(view)
from django.shortcuts import render, redirect, get_object_or_404

#this function necessitates that a user is logged in to view the page
#each function represents a view for a page so its before a function
from django.contrib.auth.decorators import login_required

#used to return a 404 error page
from django.http import Http404

#import models associated with data we need
#import Entry model because working with existing entry
from .models import Topic, Entry

#import forms associated with data we need
from .forms import TopicForm, EntryForm

#index is called in urls.py
#argument is request object received from server
#index takes requested argument and generates response (render)
 #.html is template response to request
def index(request):
    """home page for Learning Log"""
    return render(request, "learning_logs/OGindex.html")

#view page for all topics

#login required = function that requires user is logged in
#always placed before view function
#ensures that specific topics are only seen by specfic user
#also takes care of entries cuz its apart of topics
#if user not logged in we send specific URL request
# (go to diff specific page instead)
@login_required()
def topics(request):
    """Show all topics"""

    #variable for database of topics is retreived and sorted
    #attribute is based off Topic model
    #date_added is attribute of Topic class
    #filter(owner) function
        #only when current user matches owner = access to owner's topics
        #basically correlates current user to their topics
    topics =  Topic.objects.filter(owner=request.user).order_by("date_added")


    #context is dictionary of name and data
    #key is topics, value is queryset of topics
    #data is sent to template for use
    context = {"topics": topics}
    return render(request, "learning_logs/topics.html", context)


#topic_id is a new argument
#topic id accepts topic_id value integer from urls.py
@login_required()
def topic(request, topic_id):
    """Show a single topic and all its entries"""

    #Topic.objects.get() retrieves topics
    #replaced by get_object_or_404
    topic = get_object_or_404(Topic, id = topic_id)

    # Make sure topic belongs to current user
    # although topics attribute matches a user to their topics...
        # any user would still have access to topics thru URL
    # this if statement ensures user is owner of topics before showing pagge
    #wont show entries for specfic topic if user isnt owner of topic
    if topic.owner != request.user:

        # error page
        # raise = create an exception and do action
        raise Http404

    #retrieves entries for each topic(above variable)
    #order entry set, reverse denoted by minus sign (most recent)
    entries = topic.entry_set.order_by("-date_added")

    #store topic and entries for each topic in context dict
    context = {"topic": topic, "entries": entries}
    return render(request, "learning_logs/OGtopic.html", context)

#GET request = need info (blank page)
#POST request = need to give info
@login_required()
def new_topic(request):
    """Add a new topic"""

    #request is GET, so we need info (blank page)
    if request.method != "POST":

        #no data submitted; create a blank form
        #create an instance of TopicForm(blank page)
        form = TopicForm()

    #else means if request.method is POST
    #processes data submitted in form
    else:

        #instance of form which has data stored in request.POST
        #POST data submitted; process data
        form = TopicForm(data=request.POST)

        #check if form Topic has everything needed (all fields)
        #is TOpic class and is TOpicForm class satisfied
        if form.is_valid():

            #these 3 lines match a new_topic to current user
                #like how new entry matches to current topic
            # writes data from form to database
            #also sets to variable new_topic
            new_topic = form.save(commit=False)

            #attribute for new_topic.owner is set to match current user
            new_topic.owner = request.user

            #saves new_topic and the user that its matched with
            new_topic.save()


            #redirect to topics page after finished creating a topic
            return redirect("learning_logs:topics")


    #display blank or invalid form
    #blank form gets sent as variable in context dict
    context = {"form": form}
    return render(request, "learning_logs/new_topic.html", context)

#topic_id is parameter cuz we want to match it with value from URL
@login_required()
def new_entry(request, topic_id):
    """Add a new entry for a particular topic"""

    #variable is retrieved topic from Topics with matching id to URL id
    topic = Topic.objects.get(id=topic_id)

    if request.method != "POST":

        #GET method = we need to sumbit data, create empty form instance
        #No data submitted, create blank form
        form = EntryForm()

    else:
        #POST data submitted; process data
        #inctance of EmptyForm with posted data
        form = EntryForm(data=request.POST)


        if form.is_valid():

            #newly created entry object
            #commit =False means dont save to database yet
            new_entry = form.save(commit=False)

            #topic value for new_entry object is topic from start of function
            #ensures topic value correlates with entry value
            new_entry.topic = topic

            #saves new entry to database
            new_entry.save()

            #takes us to different view page
            #main page for specific topic with specific id
            return redirect("learning_logs:topic", topic_id=topic_id)

    #Display a blank or invalid form
    context = {"topic": topic, "form": form}
    return render(request, "learning_logs/new_entry.html", context)

@login_required()
def edit_entry(request, entry_id):
    """Edit an existing entry"""

    #get entry object that will be edited
    #entry object has id matching entry_id specified in URL request
    entry = Entry.objects.get(id=entry_id)

    #get topic associated with entry
    topic = entry.topic

    #another way other users would have access to others' entries
    if topic.owner != request.user:
        raise Http404

    #GET request, instead of empty form we call requested entry to edit
    if request.method != "POST":

        #create form with info from called/existing entry
        #Intitial request;
        form = EntryForm(instance=entry)

    else:
        #POST data submitted; process data
        #modify form with initial entry as base and request.POST as new data
        #basically creates a form combining OG form and new input
        form = EntryForm(instance=entry, data=request.POST)

        #entry is already associated with topic
        # we dont need arguments like new_entry view
        if form.is_valid():
            form.save()

            #return to specific topic page
            return redirect("learning_logs:topic", topic_id=topic.id)

    #context dict, we need all these keys and its values for HTML
    context = {"entry": entry, "topic": topic, "form": form}

    #generate template
    return render(request, "learning_logs/edit_entry.html", context)

learning_logs/templates/learning_logs/OGbase.html
<!-- This is the base template
contains repeated webpage elements
other pages inherit from this-->

<!-- {%} is link generator, template tag
    specific template tag generates URL which matches "index"
    basically when you click the link, it takes you to OGindex.html
   file is in learning_logs/urls.py,
   learning_logs: is from appname variable
    -->

<!-- THIS HTML ISNT USED, REPLACED BY BASE.MTML
IT HAS OG NOTES FOR STARTING A BASE HTML FILE
    -->


<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -

    <!--every page now has topics link-->
    <!--generate link matching URL pattern with topics-->
    <a href="{% url 'learning_logs:topics' %}">Topics</a> -

    <!-- if statement for if person is already logged in-->
    {% if user.is_authenticated %}

        <!-- user is automatically created by django-->
        Hello, {{ user.username }}.

        <!-- link for loging out, default logout view/URL is called-->
        <a href="{% url 'users:logout' %}">Log out</a>

    <!-- if not, user is not logged in-->
    {% else %}
        <!--display link to register page-->
        <a href="{% url 'users:register' %}">Register</a> -

        <!-- users:login is default loging URL by django-->
        <a href="{% url 'users:login' %}">Log in</a>
    {% endif %}
</p>


<!-- block tags, used by child templates...
inheritors, will define content between content blocks
    -->
{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/OGindex.html
<!-- ORIGINAL TEMPLATE NOT IN USE-->

<!-- This is the template
It is what is generated when response is done by view
view function makes this visible to matched URL-->

<!-- always make sure that html files have .html,
html cuz deployed to web-->

<!-- extends tells django to inherit from specific parent template-->
{% extends "learning_logs/base.html" %}


<!-- define content previously defined in parent template
   everything that's new in file goes between content block -->
{% block content %}

<p>Learning Log helps you keep track of your learning.
for any topic you're learning about</p>

{% endblock content %}

learning_logs/templates/learning_logs/OGtopic.html
<!--THIS HTML FILE IS NO LONGER IN USE
IT IS REPLACED BY TOPIC.HTML BUT HAS OG NOTES-->

{% extends 'learning_logs/base.html' %}

{% block content %}

<!--show current topic displayed-->
<!--context value for topic key-->
  <p>Topic: {{ topic }}</p>

  <p>Entries:</p>
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>

<!--bulleted list for entries-->
  <ul>

<!--loop thru entries-->
  {% for entry in entries %}

   <!--list items, date added and text for entry-->
    <li>

        <!-- value of date_added attribute
        (|) filter mods value to specific format, specific way to show date-->
      <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>

        <!--display text
        (|) filter breaks lines accordingly-->
      <p>{{ entry.text|linebreaks }}</p>

      <!--link for each entry to be able to edit entry
       entry id matches entry object to url-->
      <p>
        <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>
      </p>
    </li>
  {% empty %}
    <li>There are no entries for this topic yet.</li>
  {% endfor %}
  </ul>

{% endblock content %}

learning_logs/templates/learning_logs/base.html
<!--load template tags for bootstrap
basically importing bootstrap to this file
    -->
{% load bootstrap4 %}

<!--declare file as HTML
file is written in english
    -->
<!DOCTYPE html>
<html lang="en">

<!-- head and body are 2 parts of HTML file-->
<!-- head of HTML file doesnt display anything for page-->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1,
        shrink-to-fit=no">

    <!-- title indicates what is shown in tab bar, when website is open-->
    <title>Learning Log</title>

    <!-- load template tags for bootstrap
    css is style files
    javscript is for interactive behavior with page-->
    {% bootstrap_css %}
    {% bootstrap_javascript jquery="full" %}

    <!-- end of head part-->
</head>

<!-- body is what is displayed on page-->
<body>

<!-- navigation bar is top or side of page with tabs(links) to other pages
other pages are usually within same site-->

    <!-- <nav indicates navigation links section
    navbar inidcates navigation bar itself
    navbar-expand-md indicates size of bar
    light means bar and background are of light shade
    mg creates some space between navbar and rest of page -->
    <nav class="navbar navbar-expand-md navbar-light bg-light mb-4 border">

        <!--first link/aspect of navigation bar
         Name is Learning Log with link to home page/index
         navbar-brand makes it stand out more than other links-->
        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
            Learning Log</a>

        <!--collapse means nav bar will collapse when navbar is too narrow
        if browser window is too narrow, button replaces navbar
         user can click on button and then navbar would drop down veritcally
         -->
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target = "#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span></button>

        <!--new section of navbar separate from first Learning Log link
        new section defined by division(div)
        this section will be what's collapsed
        division also takes up entire block (width) of space-->
        <div class="collapse navbar-collapse" id="navbarCollapse">

            <!--define new set of links
            links are automatically pushed left-->
            <ul class="navbar-nav mr-auto">

                <!--defines item in set as a link
                the link is for Topics page-->
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'learning_logs:topics' %}">
                        Topics</a></li>
            </ul>

            <!--new set of links pushed to right of page-->
            <ul class="navbar-nav ml-auto">

                <!--separates whats shown if user is logged in or not-->
                {% if user.is_authenticated %}

                <!--display text element span that says hello
                span is opposite from div in that it is apart of a line/block-->
                    <li class="nav-item">
                        <span class="navbar-text">Hello, {{ user.username }}.</span>
                    </li>

                <!--These links are same as Topics link above, item in a set
                take users to page if clicked on-->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
                {% endif %}
            </ul>

<!--end of division element that would collapse-->
        </div>

  <!--end of navigation bar-->
    </nav>

<!--define main content of page
container groups elements of page like navbar, header, footer-->
<main role="main" class="container">

    <!--page_header division block, Title for pages
    pb specfies padding or space content of block and block itself
    mb specifeis space between blocks, we specify space only at bottom -->
    <div class="pb-2 mb-2 border-bottom">

        <!--content of this title block,
        will be filled in by specifics (title) of other pages -->
        {% block page_header %}{% endblock page_header %}
    </div>

    <!--division block for content of page itself, not title-->
    <div>

        <!--will be filled in by specifics (data) of other pages-->
        {% block content %}{% endblock content %}
    </div>
</main>

</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
<!--similar to new entry template -->
{% extends "learning_logs/base.html" %}

{%block content%}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <p>Edit entry:</p>

    <!--sends form to edit_entry function as POST
     entry.id matches entry object to correct id in view-->
    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

<!--Home page
We're only filling in content for the page header part of base
We're not doing anything with the content part of base-->
{% block page_header %}

<!--division element defined as a jumbotron
jumbotron is specific bootstrp selector
everything in block is element apart of jumbotron-->
    <div class="jumbotron">

        <!--h1 means first level/main header
        display-3 is specific style for text
        Track your learning is text-->
        <h1 class="display-3">Track your learning.</h1>

        <!--lead is also specific style for text
        paragraph is basic text format-->
        <p class="lead">Make your own Learning Log, and keep a list of
        the topics you're learning about. Whenever you learn something
        new about a topic, make an entry summarizing what you've learned.</p>

        <!--this part is a button that says register
        a indicates hyperlink which means it will take us to another page
        href is always part of <a as desitnation link
        btn-lg and primary make it big and blue
        &raquo creates two arros next to "Register"-->
        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}"
           role=button">Register &raquo;</a>
    </div>
{% endblock page_header %}

learning_logs/templates/learning_logs/new_entry.html
<!--Very similar to new_topic template -->
{% extends "learning_logs/base.html" %}

{% block content %}

<!-- show Topic name with link attached to it to main page for topic-->
    <p><a href="{% url 'learning_logs:topic' topic.id %}"> {{topic}}</a></p>


    <p>Add a new entry:</p>

    <!-- Define HTML form, send submitted data to new_entry function as POST
    topic id value is included to match entry with topic-->
    <form action="{% url 'learning_logs:new_entry' topic.id %}" method="post">

        <!--cross site request forgery -->
        {% csrf_token %}

        <!-- text box for entry-->
        {{ form.as_p }}
        <button name="submit">Add entry</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}

{% block content %}
    <p>Add a new topic:</p>

<!--define HTML form
 action tells browser where to send submitted data, new_topic view
 method tells browser to send it as a POST-->
    <form action="{% url 'learning_logs:new_topic' %}" method='post'>

<!--cross-site request forgery,
 prevent unauthorized attacks-->
        {% csrf_token %}

<!--display form in paragraph format
 displays text box for info to be submitted
 "form" is variable form from new_topic function
 "form" is blank instance of Topic-->
        {{ form.as_p }}

        <!-- define a submit button for forms
        name defines what button does
        Add topic is what is displayed on screen-->
        <button name="submit">Add topic</button>
    </form>

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

<!--specfic Topic is now in page header block with h3 size-->
{% block page_header %}
    <h3>{{ topic }}</h3>
{% endblock page_header %}

{% block content %}
  <p>
    <a href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>

<!--replace ul and li which ordered the elements in a list
each element is now a division element-->
  {% for entry in entries %}

<!--card has two sub elements-->
    <div class="card mb-3">

        <!--card header contains date and link
        h4 means its 4th level size
        small means edit entry link is made smaller relative to date added-->
        <h4 class="card-header">
            {{ entry.date_added|date:'M d, Y H:i' }}
            <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">
                edit entry</a></small>
        </h4>

        <!--2nd element is body which is also a division element
        places entries in a simple box-->
        <div class="card-body">
            {{ entry.text|linebreaks }}
        </div>
    </div>

  {% empty %}
    <p>There are no entries for this topic yet.</p>
  {% endfor %}


{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

<!--We don't need a load bootstrap tag cuz we're not using any bootstrap
template tags like "buttons"-->

<!--We moved Topics title to page_header block instead of content
also changed it from basic p text to h1-->
{% block page_header %}
    <h1>Topics</h1>
{% endblock page_header %}

{% block content %}



<!--ul denotes unordered bulleted list -->
    <ul>

        <!--for loop template tag
        loops thru topics in context dict-->
        {% for topic in topics %}

        <!--double braces means to print variable-->
        <!--li means its a list item,
        each topic is bulleted item in list-->
            <li><h3>
                <a href="{% url 'learning_logs:topic' topic.id %}">{{topic}}</a>

         <!--make topic size a little larger with h3-->
            </h3></li>

        <!--empty template tag
        if empty list print no topics... statement-->
        {% empty %}

        <!--increase size of statement to h3-->
            <li><h3>No topics have been added yet.</h3></li>

        <!--mandatory for loop closure-->
        {% endfor %}
    </ul>

<!--link to new_topic page on topics page
 Add a new topic is what shows and
 if clicked takes us to new_topic url then view then template-->
<h3><a href="{% url 'learning_logs:new_topic' %}">

    <!--Increase size of add a new topic link to h3-->
    Add a new topic</a></h3>

{% endblock content %}